{% set name = "backpack" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/backpack-{{ version }}.tar.gz
  sha256: 0162cf7b34c810ba4ddbbd32a1e5e804ef96fcf2fea5ce2848aa4950770d3893

build:
  number: 1004
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - cython
    - pip
    - python
  run:
    - python
    - simplejson

test:
  imports:
    - backpack
    - backpack._utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdispater/backpack
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Useful utilities for Python.
  description: "Useful utilities for Python. Supports Python 2.7+ and 3.2+."
  doc_url: https://github.com/sdispater/backpack
  dev_url: https://github.com/sdispater/backpack

extra:
  recipe-maintainers:
    - nick-youngblut
