{% set name = "backpack" %}
{% set version = "0.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '0162cf7b34c810ba4ddbbd32a1e5e804ef96fcf2fea5ce2848aa4950770d3893'

build:
  number: 1001
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - simplejson
  run:
    - python
    - simplejson

test:
  imports:
    - backpack
    - backpack._utils
    - backpack.collections
  requires:
    - pytest

about:
  home: https://github.com/sdispater/backpack
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Useful utilities for Python.
  description: "Useful utilities for Python. Supports Python 2.7+ and 3.2+."
  doc_url: https://github.com/sdispater/backpack
  dev_url: https://github.com/sdispater/backpack

extra:
  recipe-maintainers:
    - nick-youngblut
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
