appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kzK0iqj0oV77bugM7A071l4doPJKxJ5kEa66QnmU1AMRzKuCk1eiHM61wvgQwX6yW4//eO3omuIx8D7GQ4HsadVzfUG+DIAt2KVw4oYpiTWHbye7OtO3e+ao7pwApZr4dZeDxelhZdKjyW860UWV9sOiYCj0pT3WtyngFJVwRZBEGObD42ttiyEhhsjT+8KeZB+uA77lrbQLU7JiuNbHGEq2VgXIpeipztdiUOfVrdICoH5g7GSdm7G2+ITQ4Oiz9WRYqMymu4XrcMmvi/7N2Xvf2Z9kw3W6U3u67hkmWv8vVNuIi/rRyD26gUrhVFX+lKOy8HZPvIzfGpCSrdiP0bnguIwTNz1mwcgGhIwtFNsWr1ExBWusbh7wU9ndL7onap8R2c1huH77XxFC3d7TO66O/QXUIgAaJ7kgIw9mpeZ51KRvcnwkvS+RrTkdQfxffjJeejvRrpp5sL25fd4gkMLLPTeUqRGaMn0jqfdwlKgmUPRit4AwaD1NN0HSeiSkYqW1b+hoCjhGCFbucvKbqPgddFSfjxoD21HRTseTYwQ+/TyrdYdYA2HmCo7j34vuqRb7gnFiauYU+X2m2pqbk8np4NkO9eQN6EwuQSiiACEw0Qa4UQn4hKDF8ADuw/t2uwv62I2ymDRAt5AnaNxSP6L843h2KRXidKnxhK5lLiY=}
conda_forge_output_validation: true
