travis:
  secure:
    BINSTAR_TOKEN: KTSw0LRlPU/TzE8EcDjF/BguSSRJCDqG3F8opmlMyo0uYIqLjFA3fOViz44XK/xO/OLjCCgCxLB3zUhWVgiuiziK1TOMqO76fZYTE9Q0bsYwuXRNjn5ObrFSNJbHbwSjxRsqang6Wwd/tS55YbhWV0W3c0fw+7otydmdIM3a5TGQrBrne7XCy9kpvr5l82E7cVcM46STR0cIeeTc8tvGERVv4VT4U08COtH0xLJ3leVux3guwwLB2OfEWt50wjSpkQrhFZlhUiWS+tmLKgvL8XVQEZfPDrBO0os2lcajtVYV7WBKL0HCVMLhTSl/R4j5hPpGJnTWy4mpUiswko7LcbQJKtuO8gOyEnhfv20Io/YiyeB9AyGhzxxdXeDoJPnS7ZHxdn2I7F0aD6R4GM4ZuIp2IyREzSd3vVSu0Ry+i8nY6giou+jkgWg9qihhXRQxNa59yoZjnNtlz2vTBKZnQtlHScdeWn8WekrdKE9XYk0kkO5GjkB9WTlcnyS/jsfgmizXuwpVyo56IO2LzUR5WGX6zmDDTxqS7dmydHpkI+2vLavwSu0wRbGIhjlgk4OY4ZpT13GV9dR6+ekBKvNBp/eHiNUtjHmr9kGBBpuC3EKneKOsV0xIm25YkegPUfEHw7EHt9nss6GtueDvB18Ob32aCIBTxU+ycNWjece6lFg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
